import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
}

minecraft {
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'
}

sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.register("signJar") {
    dependsOn jar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = tasks.jar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}

jar.finalizedBy 'signJar'

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
